#!/usr/bin/env node
import type { GeneratorOptions } from "@prisma/generator";
import { DMMF, generatorHandler } from "@prisma/generator-helper";
import fs from "fs/promises";
import { readFileSync } from "fs";
import path from "path";

// The suppression directives exempt the generated implementation from type
// checking and linting, mirroring Prisma's own generated client header.
// `// @ts-nocheck` in particular avoids a large type-instantiation cost on
// big schemas (see #29); exported signatures still type-check consumer call
// sites.
function headerFor(noCheck: boolean) {
  return (
    `// This file was generated by prisma-effect-generator, do not edit manually.\n` +
    (noCheck
      ? `/* eslint-disable */\n// biome-ignore-all lint: generated file\n// @ts-nocheck\n`
      : "")
  );
}

// Utility function to convert PascalCase to camelCase
function toCamelCase(str: string) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

// Utility function to capitalize the first character (inverse of toCamelCase)
function capitalize(str: string) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// The major version of `effect` the generated code targets. v3 and v4 differ in
// their service/runtime APIs (see `variantsFor`), so the generator emits code
// matching whichever `effect` the consuming project has installed.
type EffectMajor = 3 | 4;

// Extract the supported EffectMajor from a version-ish string ("4.0.0-beta.83",
// "^3.19", "10"). Reads the first run of digits as the major, so multi-digit
// majors parse correctly; only a leading major of 4+ selects v4. Anything that
// doesn't parse to >= 4 — including malformed values — falls back to v3, the
// long-standing stable line.
function majorOf(version: string): EffectMajor {
  return Number(version.match(/\d+/)?.[0]) >= 4 ? 4 : 3;
}

// Resolve the consuming project's installed `effect` major version. Returns
// `undefined` when `effect` can't be resolved, so callers can fall back.
function resolveEffectMajor(searchPaths: string[]): EffectMajor | undefined {
  try {
    // require.resolve is the reliable way to find the consumer's installed
    // effect from this CommonJS generator; the JSON is then read with fs.
    const pkgPath = require.resolve("effect/package.json", {
      paths: searchPaths,
    });
    const version: string = JSON.parse(readFileSync(pkgPath, "utf8")).version;
    return majorOf(version);
  } catch {
    return undefined;
  }
}

// Decide which effect major to target: an explicit `effectVersion` config wins,
// otherwise auto-detect from the consumer's installed `effect`, otherwise fall
// back to v3.
function determineEffectMajor(
  configVersion: string | string[] | undefined,
  searchPaths: string[],
): EffectMajor {
  const explicit = Array.isArray(configVersion)
    ? configVersion[0]
    : configVersion;
  if (typeof explicit === "string" && explicit.trim() !== "") {
    return majorOf(explicit);
  }
  return resolveEffectMajor(searchPaths) ?? 3;
}

// Prisma passes generator config values as strings (or string arrays for
// repeated keys); accept only "true"/"false".
function parseBooleanConfig(
  value: string | string[] | undefined,
  name: string,
  defaultValue: boolean,
): boolean {
  const raw = Array.isArray(value) ? value[0] : value;
  if (raw === undefined) {
    return defaultValue;
  }
  if (raw === "true") {
    return true;
  }
  if (raw === "false") {
    return false;
  }
  throw new Error(
    `effect-prisma-generator: ${name} must be "true" or "false". Got "${raw}".`,
  );
}

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/effect.ts",
      prettyName: "Prisma Effect Generator",
    };
  },

  async onGenerate(options: GeneratorOptions) {
    const models = options.dmmf.datamodel.models;
    const outputPath = options.generator.output?.value;
    const clientImportPath = options.generator.config.clientImportPath;

    if (!outputPath) {
      throw new Error("effect-prisma-generator: No outputPath specified");
    }
    if (Array.isArray(clientImportPath)) {
      throw new Error(
        "effect-prisma-generator: clientImportPath must be a string. Array given.",
      );
    }
    if (typeof clientImportPath !== "string") {
      throw new Error("effect-prisma-generator: No clientImportPath specified");
    }
    if (!outputPath.toLowerCase().endsWith(".ts")) {
      throw new Error("effect-prisma-generator: outputPath must be a ts file");
    }

    const hasTypedSql = [options.generator, ...options.otherGenerators].some(
      (g) => g.previewFeatures.includes("typedSql"),
    );

    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    const effectMajor = determineEffectMajor(
      options.generator.config.effectVersion,
      [outputDir, process.cwd()],
    );

    // Intentionally undocumented escape hatch: this repo's test suite sets
    // noCheck = "false" to type-check generated output as-is.
    const noCheck = parseBooleanConfig(
      options.generator.config.noCheck,
      "noCheck",
      true,
    );

    await generateUnifiedService(
      [...models],
      options.dmmf.mappings.modelOperations,
      outputPath,
      clientImportPath,
      hasTypedSql,
      effectMajor,
      noCheck,
    );
  },
});

function generateRawSqlOperations(hasTypedSql: boolean) {
  const typedSqlOperation = hasTypedSql
    ? `

    $queryRawTyped: <T>(typedQuery: runtime.TypedSql<unknown[], T>) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawTyped(typedQuery),
          catch: (error) => mapError(error, "$queryRawTyped", "Prisma")
        }),
      ),`
    : "";

  return `
    $executeRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$executeRaw(args[0], ...args.slice(1)) : client.$executeRaw(args)),
          catch: (error) => mapError(error, "$executeRaw", "Prisma")
        }),
      ),

    $executeRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$executeRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$executeRawUnsafe", "Prisma")
        }),
      ),

    $queryRaw: (args: Prisma.Sql | [Prisma.Sql, ...any[]]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => (Array.isArray(args) ? client.$queryRaw(args[0], ...args.slice(1)) : client.$queryRaw(args)),
          catch: (error) => mapError(error, "$queryRaw", "Prisma")
        }),
      ),

    $queryRawUnsafe: (query: string, ...values: any[]) =>
      Effect.flatMap(clientOrTx(client), client =>
        Effect.tryPromise({
          try: () => client.$queryRawUnsafe(query, ...values),
          catch: (error) => mapError(error, "$queryRawUnsafe", "Prisma")
        }),
      ),${typedSqlOperation}`;
}

function generateModelOperations(
  models: DMMF.Model[],
  modelOperations: DMMF.Mappings["modelOperations"],
) {
  const mappingByModel = new Map(
    modelOperations.map((m) => [m.model, m as Record<string, unknown>]),
  );
  return models
    .map((model) => {
      const modelName = model.name;
      const modelNameCamel = toCamelCase(modelName);
      // Prisma capitalizes the first letter only for *AggregateArgs / *GroupByOutputType
      const modelNameCapitalized = capitalize(modelName);
      // A model with a required `Unsupported(...)` field (e.g. a pgvector
      // `vector` column) cannot be created through the typed client, so Prisma
      // omits its create/createMany/createManyAndReturn/upsert operations and
      // their `*Args` types. Emit each operation only when its DMMF mapping
      // exists; Prisma 7 names the single-record mappings `createOne`/
      // `upsertOne`, older majors used `create`/`upsert`.
      const mapping = mappingByModel.get(modelName) ?? {};
      const hasOp = (...keys: string[]) =>
        keys.some((key) => Boolean(mapping[key]));

      const createOp = hasOp("createOne", "create")
        ? `
      create: <T extends Prisma.${modelName}CreateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.create(args),
            catch: (error) => mapCreateError(error, "create", "${modelName}")
          }),
        ),
`
        : "";

      const createManyOp = hasOp("createMany")
        ? `
      createMany: <T extends Prisma.${modelName}CreateManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.createMany(args),
            catch: (error) => mapCreateError(error, "createMany", "${modelName}")
          }),
        ),
`
        : "";

      const createManyAndReturnOp = hasOp("createManyAndReturn")
        ? `
      createManyAndReturn: <T extends Prisma.${modelName}CreateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CreateManyAndReturnArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.createManyAndReturn(args),
            catch: (error) => mapCreateError(error, "createManyAndReturn", "${modelName}")
          }),
        ),
`
        : "";

      const upsertOp = hasOp("upsertOne", "upsert")
        ? `
      upsert: <T extends Prisma.${modelName}UpsertArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpsertArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.upsert(args),
            catch: (error) => mapCreateError(error, "upsert", "${modelName}")
          }),
        ),
`
        : "";

      return `    ${modelNameCamel}: {
      findUnique: <T extends Prisma.${modelName}FindUniqueArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindUniqueArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findUnique(args),
            catch: (error) => mapFindError(error, "findUnique", "${modelName}")
          }),
        ),

      findUniqueOrThrow: <T extends Prisma.${modelName}FindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindUniqueOrThrowArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findUniqueOrThrow(args),
            catch: (error) => mapFindOrThrowError(error, "findUniqueOrThrow", "${modelName}")
          }),
        ),

      findFirst: <T extends Prisma.${modelName}FindFirstArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindFirstArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findFirst(args),
            catch: (error) => mapFindError(error, "findFirst", "${modelName}")
          }),
        ),

      findFirstOrThrow: <T extends Prisma.${modelName}FindFirstOrThrowArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindFirstOrThrowArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findFirstOrThrow(args),
            catch: (error) => mapFindOrThrowError(error, "findFirstOrThrow", "${modelName}")
          }),
        ),

      findMany: <T extends Prisma.${modelName}FindManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}FindManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.findMany(args),
            catch: (error) => mapFindError(error, "findMany", "${modelName}")
          }),
        ),
${createOp}${createManyOp}${createManyAndReturnOp}
      delete: <T extends Prisma.${modelName}DeleteArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}DeleteArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.delete(args),
            catch: (error) => mapDeleteError(error, "delete", "${modelName}")
          }),
        ),

      update: <T extends Prisma.${modelName}UpdateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.update(args),
            catch: (error) => mapUpdateError(error, "update", "${modelName}")
          }),
        ),

      deleteMany: <T extends Prisma.${modelName}DeleteManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}DeleteManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.deleteMany(args),
            catch: (error) => mapDeleteManyError(error, "deleteMany", "${modelName}")
          }),
        ),

      updateMany: <T extends Prisma.${modelName}UpdateManyArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateManyArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.updateMany(args),
            catch: (error) => mapUpdateManyError(error, "updateMany", "${modelName}")
          }),
        ),

      updateManyAndReturn: <T extends Prisma.${modelName}UpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}UpdateManyAndReturnArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.updateManyAndReturn(args),
            catch: (error) => mapUpdateManyError(error, "updateManyAndReturn", "${modelName}")
          }),
        ),
${upsertOp}
      // Aggregation operations
      count: <T extends Prisma.${modelName}CountArgs>(args: Prisma.SelectSubset<T, Prisma.${modelName}CountArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.count(args),
            catch: (error) => mapFindError(error, "count", "${modelName}")
          }),
        ),

      aggregate: <T extends Prisma.${modelNameCapitalized}AggregateArgs>(args: Prisma.SelectSubset<T, Prisma.${modelNameCapitalized}AggregateArgs>) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.aggregate(args),
            catch: (error) => mapFindError(error, "aggregate", "${modelName}")
          }),
        ),

      groupBy: <
        T extends Prisma.${modelName}GroupByArgs,
        HasSelectOrTake extends Prisma.Or<
          Prisma.Extends<'skip', Prisma.Keys<T>>,
          Prisma.Extends<'take', Prisma.Keys<T>>
        >,
        OrderByArg extends Prisma.True extends HasSelectOrTake
          ? { orderBy: Prisma.${modelName}GroupByArgs['orderBy'] }
          : { orderBy?: Prisma.${modelName}GroupByArgs['orderBy'] },
        OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
        ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
        ByValid extends Prisma.Has<ByFields, OrderFields>,
        HavingFields extends Prisma.GetHavingFields<T['having']>,
        HavingValid extends Prisma.Has<ByFields, HavingFields>,
        ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
        InputErrors extends ByEmpty extends Prisma.True
        ? \`Error: "by" must not be empty.\`
        : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
              ? \`Error: Field "\${P}" used in "having" needs to be provided in "by".\`
              : [
                  Error,
                  'Field ',
                  P,
                  \` in "having" needs to be provided in "by"\`,
                ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
              }[OrderFields]
          : 'Error: If you provide "take", you also need to provide "orderBy"'
        : 'skip' extends Prisma.Keys<T>
        ? 'orderBy' extends Prisma.Keys<T>
          ? ByValid extends Prisma.True
            ? {}
            : {
                [P in OrderFields]: P extends ByFields
                  ? never
                  : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
              }[OrderFields]
          : 'Error: If you provide "skip", you also need to provide "orderBy"'
        : ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : \`Error: Field "\${P}" in "orderBy" needs to be provided in "by"\`
          }[OrderFields]
      >(args: Prisma.SubsetIntersection<T, Prisma.${modelName}GroupByArgs, OrderByArg> & InputErrors) =>
        Effect.flatMap(clientOrTx(client), client =>
          Effect.tryPromise({
            try: () => client.${modelNameCamel}.groupBy(args as any) as Prisma.PrismaPromise<
              Array<Prisma.PickEnumerable<Prisma.${modelNameCapitalized}GroupByOutputType, T["by"]> & {
                  [P in keyof T &
                    keyof Prisma.${modelNameCapitalized}GroupByOutputType]: P extends "_count"
                    ? T[P] extends boolean
                      ? number
                      : Prisma.GetScalarType<
                          T[P],
                          Prisma.${modelNameCapitalized}GroupByOutputType[P]
                        >
                    : Prisma.GetScalarType<
                        T[P],
                        Prisma.${modelNameCapitalized}GroupByOutputType[P]
                      >;
                }>>,
            catch: (error) => mapFindError(error, "groupBy", "${modelName}")
          }),
        ),
    }`;
    })
    .join(",\n\n");
}

// The pieces of the emitted service that differ between effect v3 and v4. The
// rest of the generated file is identical across majors.
function variantsFor(major: EffectMajor) {
  if (major === 3) {
    return {
      imports:
        `import { Cause, Context, Data, Effect, Exit, Layer, Option, Runtime } from "effect"\n` +
        `import { Service } from "effect/Effect"`,
      tag: (self: string, type: string, id: string = self) =>
        `Context.Tag("${id}")<\n  ${self},\n  ${type}\n>()`,
      serviceConstructor: `Service<PrismaService>()`,
      serviceConfigKey: "effect",
      txContextVar: "runtime",
      txContextExpr: "Effect.runtime<R>()",
      txRun: "Runtime.runPromiseExit(runtime)",
      // effect v3's `Effect.Service` already provides a `.Default` layer.
      serviceStatics: "",
    };
  }
  return {
    imports: `import { Cause, Context, Data, Effect, Exit, Layer, Option } from "effect"`,
    tag: (self: string, type: string, id: string = self) =>
      `Context.Service<\n  ${self},\n  ${type}\n>()("${id}")`,
    serviceConstructor: `Context.Service<PrismaService>()`,
    serviceConfigKey: "make",
    txContextVar: "services",
    txContextExpr: "Effect.context<R>()",
    txRun: "Effect.runPromiseExitWith(services)",
    // effect v4's `Context.Service` has no auto `.Default`; expose `.layer`.
    serviceStatics: "\n  static readonly layer = Layer.effect(this, this.make)",
  };
}

async function generateUnifiedService(
  models: DMMF.Model[],
  mappings: DMMF.Mappings["modelOperations"],
  outputPath: string,
  clientImportPath: string,
  hasTypedSql: boolean,
  major: EffectMajor,
  noCheck: boolean,
) {
  const rawSqlOperations = generateRawSqlOperations(hasTypedSql);
  const modelOperations = generateModelOperations(models, mappings);
  const v = variantsFor(major);

  const runtimeImport = hasTypedSql
    ? `\nimport * as runtime from "@prisma/client/runtime/client"`
    : "";

  const serviceContent = `${headerFor(noCheck)}
${v.imports}
import { Prisma, PrismaClient } from "${clientImportPath}"${runtimeImport}

export class PrismaClientService extends ${v.tag("PrismaClientService", "PrismaClient")} {}

// A client created with client.$extends(...) (e.g. @prisma/extension-accelerate).
// Its static type is not structurally compatible with PrismaClient — extended
// delegates use different generic signatures — but at runtime an extension
// wraps the client rather than stripping it, so every operation this service
// uses (and the lifecycle methods) remain available. Requiring every model
// delegate property (via TypeMap) makes a client generated from a different
// schema, or an incomplete mock, a compile error, while still accepting any
// extension of this schema's client.
export type ExtendedPrismaClientLike = {
  $transaction(...args: ReadonlyArray<any>): Promise<any>
  $queryRaw(...args: ReadonlyArray<any>): Promise<any>
  $executeRaw(...args: ReadonlyArray<any>): Promise<any>
} & {
  [K in Prisma.TypeMap["meta"]["modelProps"]]: unknown
}

// Builds the PrismaClientService layer from a plain or extended client (#17).
// The cast is sound at runtime (see ExtendedPrismaClientLike above), but an
// extension's type-level changes (e.g. result extensions adding computed
// fields, or extra query args like Accelerate's cacheStrategy) are not
// reflected in the service's types; at runtime all operations go through the
// extended client and behave per the extension.
export const layerFromPrismaClient = (
  client: PrismaClient | ExtendedPrismaClientLike,
) => Layer.succeed(PrismaClientService, client as PrismaClient)

export class PrismaTransactionClientService extends ${v.tag("PrismaTransactionClientService", "Prisma.TransactionClient")} {}

export class PrismaUniqueConstraintError extends Data.TaggedError("PrismaUniqueConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaForeignKeyConstraintError extends Data.TaggedError("PrismaForeignKeyConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRecordNotFoundError extends Data.TaggedError("PrismaRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelationViolationError extends Data.TaggedError("PrismaRelationViolationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaRelatedRecordNotFoundError extends Data.TaggedError("PrismaRelatedRecordNotFoundError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaTransactionConflictError extends Data.TaggedError("PrismaTransactionConflictError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueTooLongError extends Data.TaggedError("PrismaValueTooLongError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaValueOutOfRangeError extends Data.TaggedError("PrismaValueOutOfRangeError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaDbConstraintError extends Data.TaggedError("PrismaDbConstraintError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaConnectionError extends Data.TaggedError("PrismaConnectionError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaMissingRequiredValueError extends Data.TaggedError("PrismaMissingRequiredValueError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export class PrismaInputValidationError extends Data.TaggedError("PrismaInputValidationError")<{
  cause: Prisma.PrismaClientKnownRequestError
  operation: string
  model: string
}> {}

export type PrismaCreateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaDeleteError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

export type PrismaFindOrThrowError =
  | PrismaConnectionError
  | PrismaRecordNotFoundError

export type PrismaFindError =
  | PrismaConnectionError

export type PrismaDeleteManyError =
  | PrismaForeignKeyConstraintError
  | PrismaRelationViolationError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaUpdateManyError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaTransactionConflictError

export type PrismaError =
  | PrismaValueTooLongError
  | PrismaUniqueConstraintError
  | PrismaForeignKeyConstraintError
  | PrismaDbConstraintError
  | PrismaInputValidationError
  | PrismaMissingRequiredValueError
  | PrismaRelationViolationError
  | PrismaRelatedRecordNotFoundError
  | PrismaValueOutOfRangeError
  | PrismaConnectionError
  | PrismaRecordNotFoundError
  | PrismaTransactionConflictError

// Generic mapper for raw operations and fallback
const mapError = (error: unknown, operation: string, model: string): PrismaError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  // Unknown errors are not handled and will be treated as defects
  throw error;
}

// Specific mappers to narrow error types per operation

// Create, Upsert
const mapCreateError = (error: unknown, operation: string, model: string): PrismaCreateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Update
const mapUpdateError = (error: unknown, operation: string, model: string): PrismaUpdateError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2015":
      case "P2018":
        return new PrismaRelatedRecordNotFoundError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Delete
const mapDeleteError = (error: unknown, operation: string, model: string): PrismaDeleteError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// FindOrThrow
const mapFindOrThrowError = (error: unknown, operation: string, model: string): PrismaFindOrThrowError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2025":
        return new PrismaRecordNotFoundError({ cause: error, operation, model });
    }
  }
  throw error;
}

// Find
const mapFindError = (error: unknown, operation: string, model: string): PrismaFindError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
    }
  }
  throw error;
}

// DeleteMany
const mapDeleteManyError = (error: unknown, operation: string, model: string): PrismaDeleteManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2014":
        return new PrismaRelationViolationError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

// UpdateMany
const mapUpdateManyError = (error: unknown, operation: string, model: string): PrismaUpdateManyError => {
  if (error instanceof Prisma.PrismaClientKnownRequestError) {
    switch (error.code) {
      case "P2000":
        return new PrismaValueTooLongError({ cause: error, operation, model });
      case "P2002":
        return new PrismaUniqueConstraintError({ cause: error, operation, model });
      case "P2003":
        return new PrismaForeignKeyConstraintError({ cause: error, operation, model });
      case "P2004":
        return new PrismaDbConstraintError({ cause: error, operation, model });
      case "P2005":
      case "P2006":
      case "P2019":
        return new PrismaInputValidationError({ cause: error, operation, model });
      case "P2011":
      case "P2012":
        return new PrismaMissingRequiredValueError({ cause: error, operation, model });
      case "P2020":
        return new PrismaValueOutOfRangeError({ cause: error, operation, model });
      case "P2024":
        return new PrismaConnectionError({ cause: error, operation, model });
      case "P2034":
        return new PrismaTransactionConflictError({ cause: error, operation, model });
    }
  }
  throw error;
}

const clientOrTx = (client: PrismaClient) => Effect.map(
  Effect.serviceOption(PrismaTransactionClientService),
  Option.getOrElse(() => client),
);

export class PrismaService extends ${v.serviceConstructor}("PrismaService", {
  ${v.serviceConfigKey}: Effect.gen(function* () {
    const client = yield* PrismaClientService;
    return {
      $transaction: <A, E, R>(
        effect: Effect.Effect<A, E, R>,
        options?: {
          maxWait?: number
          timeout?: number
          isolationLevel?: Prisma.TransactionIsolationLevel
        }
      ) =>
        Effect.gen(function* () {
          const ${v.txContextVar} = yield* ${v.txContextExpr};
          const tx = yield* Effect.serviceOption(PrismaTransactionClientService);
          return yield* Option.match(tx, {
            onSome: (tx) => effect,
            onNone: () =>  Effect.tryPromise({
              try: () =>
                client.$transaction(async (tx) => {
                  const exit = await ${v.txRun}(
                    effect.pipe(Effect.provideService(PrismaTransactionClientService, tx)) as Effect.Effect<A, E, R>,
                  )
                  if (Exit.isSuccess(exit)) {
                    return exit.value
                  }
                  throw Cause.squash(exit.cause)
                }, options),
              catch: (error) => error as E,
            }) as unknown as Effect.Effect<A, E, R>,
          })
        }),
      ${rawSqlOperations}

      ${modelOperations}
    }
  })
}) {${v.serviceStatics}
}
`;

  await fs.writeFile(outputPath, serviceContent);
}
